spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: 1946
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
logging:
  file:
    name: ${LOG_DIR:/Users/admin/Documents/Idea}/app.log
  level:
    root: warn
    spring.service: INFO
    spring.listener: INFO
    org.hibernate.sql: INFO
    org.hibernate.orm.connections.pooling: error
