spring:
 jpa:
  open-in-view: false
 datasource:
  url: jdbc:postgresql://localhost:5432/hibernate
  username: postgres
  password: 1946
  driver-class-name: org.postgresql.Driver
server:
 port: 8080
logging:
 file:
   name: src/main/resources/app.log
 level:
  root: warn
  spring.service: INFO
  org.hibernate.sql: debug